# docs/Makefile
#
# Copyright (c) 2021-2024 Bartek Kryza <bkryza@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


UPDATE_TOC := markdown-toc  --bullets "*" -i

.PHONY: toc
toc:
		$(UPDATE_TOC) architecture.md
		$(UPDATE_TOC) class_diagrams.md
		$(UPDATE_TOC) comment_decorators.md
		$(UPDATE_TOC) common_options.md
		$(UPDATE_TOC) generator_types.md
		$(UPDATE_TOC) configuration_file.md
		$(UPDATE_TOC) diagram_filters.md
		$(UPDATE_TOC) doxygen_integration.md
		$(UPDATE_TOC) include_diagrams.md
		$(UPDATE_TOC) installation.md
		$(UPDATE_TOC) interactive_svg_diagrams.md
		$(UPDATE_TOC) diagram_templates.md
		$(UPDATE_TOC) jinja_templates.md
		$(UPDATE_TOC) package_diagrams.md
		$(UPDATE_TOC) quick_start.md
		$(UPDATE_TOC) sequence_diagrams.md
		$(UPDATE_TOC) test_cases.md
		$(UPDATE_TOC) troubleshooting.md

